receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  resource:
    attributes:
    - key: compose_service
      from_attribute: service.name
      action: upsert

exporters:
  logging:
    loglevel: debug
    sampling_initial: 5
    sampling_thereafter: 200

  otlp:
    endpoint: tempo:4317
    insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resource]
      exporters: [logging, otlp]
