---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rest-client-quickstart-config
data:
  OTEL_ENDPOINT_URL: grpc://otel-collector.otel:4317

---
apiVersion: v1
kind: Service
metadata:
  name: rest-client-quickstart
  labels:
    app: rest-client-quickstart
spec:
  type: LoadBalancer
  selector:
    app: rest-client-quickstart
  ports:
    - name: http
      port: 8086
      targetPort: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rest-client-quickstart
    app.kubernetes.io/name: rest-client-quickstart
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: opentelemetry-demo
    app.kubernetes.io/managed-by: manifests
    app.kubernetes.io/created-by: admin
  name: rest-client-quickstart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-client-quickstart
  template:
    metadata:
      labels:
        app: rest-client-quickstart
    spec:
      containers:
        - name: rest-client-quickstart
          image: igoroschsimoes/rest-client-quickstart:v0.5
          resources: {}
          envFrom:
            - configMapRef:
                name: rest-client-quickstart-config
          ports:
            - name: http
              containerPort: 8086
              protocol: TCP
