---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  PORT: '4000'
  DB_CONNECTION_URL: mongodb://backend:swordfish@mongo:27017/backend
  MAIL_SERVICE_BASE_URL: http://mail-service:4100
  VERIFICATION_SERVICE_URL: verification-service:4010
  OTEL_ENDPOINT_URL: grpc://otel-collector.otel:4317

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 4000
      targetPort: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
    app.kubernetes.io/name: backend
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: opentelemetry-demo
    app.kubernetes.io/managed-by: manifests
    app.kubernetes.io/created-by: admin
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: martinnirtl/demos.opentelemetry.backend:latest
          resources: {}
          envFrom:
            - configMapRef:
                name: backend-config
          ports:
            - name: http
              containerPort: 4000
              protocol: TCP
