apiVersion: apps/v1
kind: Deployment
metadata:
  name: graylog-deploy
  namespace: graylog
  labels:
    service: graylog-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      service: graylog-deploy
  template:
    metadata:
      labels:
        service: graylog-deploy
    spec:
      containers:
      - name: graylog3
        image: graylog/graylog:3.0
        env:
        - name: GRAYLOG_PASSWORD_SECRET
          value: g0ABP9MJnWCjWtBX9JHFgjKAmD3wGXP3E0JQNOKlquDHnCn5689QAF8rRL66HacXLPA6fvwMY8BZoVVw0JqHnSAZorDDOdCk
        - name: GRAYLOG_ROOT_PASSWORD_SHA2
          value: 6d6edcea1c93df7f546cd4e736371c5794c9d7497bdc28053293c37eb8d350a3
        - name: GRAYLOG_HTTP_EXTERNAL_URI
          value: http://10.101.41.239:9000/
        - name: GRAYLOG_ELASTICSEARCH_HOSTS
          value: http://es6:9200
        - name: GRAYLOG_MONGODB_URI
          value: mongodb://mongo:27017/graylog
        ports:
        - containerPort: 9000
        - containerPort: 12201

---
apiVersion: v1
kind: Service
metadata:
  name: graylog3
  namespace: graylog
spec:
  type: ClusterIP
  selector:
    service: graylog-deploy
  ports:
  - name: "9000"
    port: 9000
    targetPort: 9000
    #nodePort: 30003
  - name: "12201"
    port: 12201
    targetPort: 12201
    #nodePort: 30004
